name: Deploy to staging

on:
  pull_request:
    types: [labeled]

env:
  IMAGE_REGISTRY_URL: ghcr.io
  DOCKER_IMAGE_NAME: oleksandrkudin-azure-ttt
  AZURE_WEBAPP_NAME: oleksandrkudin-ttt-app

jobs:
  Build:
    name: Build application and push artifact
    runs-on: ubuntu-18.04
    if: contains(github.event.pull_request.labels.*.name, 'stage')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: npm install and build webpack
        run: |
          npm install
          npm run build
          
      - name: Push artifact
        uses: actions/upload-artifact@v3
        with:
          name: webpack artifacts
          path: public/
  
  Build-Docker-Image:
    name: Build image and store in GitHub Container Registry
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: webpack artifacts
          path: public
          
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.IMAGE_REGISTRY_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{env.IMAGE_REGISTRY_URL}}/${{ github.repository }}/${{env.DOCKER_IMAGE_NAME}}
          tags: |
            type=sha,format=long,prefix=
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
           context: .
           push: true
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
           
  Deploy-to-Azure:
    name: Deploy image to Azure Webapp
    runs-on: ubuntu-latest
    needs: Build-Docker-Image
    steps:
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Login to GitHub Container Registry (ghcr)
        uses: azure/docker-login@v1
        with:
          login-server: ${{env.IMAGE_REGISTRY_URL}}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Deploy image to Webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{env.AZURE_WEBAPP_NAME}}
          images: ${{env.IMAGE_REGISTRY_URL}}/${{ github.repository }}/${{env.DOCKER_IMAGE_NAME}}:${{ github.sha }}
          
      - name: Logout from Azure
        uses: azure/CLI@v1
        with:
           inlineScript: |
            az logout
            az cache purge
            az account clear
